version: '3'

# Les dépendances : web server, database, php my admin
services:
  laravel_app:
    image: i5m4il/laravel_app_image:latest
    container_name: laravel_app
    restart: unless-stopped
    depends_on:
      - laravel_app_mysql
    working_dir: /var/www
    # Où se trouvent les fichiers dans le container
    volumes:
      - ./:/var/www
    networks:
      - laravel_app_network

  # Service Angular Frontend
  angular_frontend:

    image: zakariyaeallouche/mon-projet-angular
    container_name: angular_frontend_container
    restart: unless-stopped
    ports:
      - "4200:80"
    working_dir: /var/www
    # Où se trouvent les fichiers dans le container
    volumes:
      - ./:/var/www
    networks:
      - laravel_app_network

  # Service Nginx
  laravel_webserver:
    image: nginx:alpine
    container_name: laravel_app_network
    restart: unless-stopped
    depends_on:
      - laravel_app
    ports:
      - "6162:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/:/etc/nginx/conf.d
    networks:
      - laravel_app_network

  # Service MySQL
  laravel_app_mysql:
    image: mysql:latest
    container_name: laravel_app_mysql_container
    restart: unless-stopped
    ports:
      - "3337:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "laravel_db"
      MYSQL_USER: "laravel_user"
      MYSQL_PASSWORD: "password"
    volumes:
      - laravel_data:/var/lib/mysql   
    networks:
      - laravel_app_network

  # Service PhpMyAdmin
  laravel_app_phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: laravel_phpmyadmin_container
    restart: unless-stopped
    ports:
      - "8383:80"
    depends_on:
      - laravel_app_mysql
    environment:
      PMA_HOST: laravel_app_mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    networks:
      - laravel_app_network

  # Service Redis
  laravel_app_redis:
    image: redis:7.2-alpine
    container_name: laravel_app_redis_container
    ports:
      - "7379:6379"
    networks:
      - laravel_app_network

volumes:
  laravel_data:
    driver: local

networks:
  laravel_app_network:
    driver: bridge
