name: Laravel Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: douaemoeniss/laravel-app:latest

      - name: Copy .env.testing
        run: cp ./backend/.env.testing ./backend/.env

      - name: Run tests with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
          docker-compose exec -T laravel_app php artisan migrate --force
          docker-compose exec -T laravel_app php artisan test
          docker-compose down
