name: Jira Integration

on:
  pull_request_target:
    types: [closed]

jobs:
  update-jira-status:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Jira
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Extract Jira Issue Key
        id: extract_jira_key
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"
          
          # Look for Jira ticket pattern in PR title (e.g., PROJECT-123)
          JIRA_KEY=$(echo "$PR_TITLE" | grep -oE '[A-Z]+-[0-9]+' | head -1)
          
          # If not found in title, look in PR description
          if [ -z "$JIRA_KEY" ]; then
            JIRA_KEY=$(echo "$PR_BODY" | grep -oE '[A-Z]+-[0-9]+' | head -1)
          fi
          
          if [ -n "$JIRA_KEY" ]; then
            echo "Found Jira ticket: $JIRA_KEY"
            echo "issue=$JIRA_KEY" >> $GITHUB_OUTPUT
          else
            echo "No Jira ticket found"
            echo "issue=" >> $GITHUB_OUTPUT
          exit 0
          fi

      - name: Transition Jira Issue
        if: steps.extract_jira_key.outputs.issue != ''
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.extract_jira_key.outputs.issue }}
          transition: "Done"
