name: CD Deploy Laravel

on:
  push:
    branches:
      - SCRUM-18-deploiment-dans-un-server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/laravel/Projet_Docker
            git pull origin main
            docker compose down
            docker compose up -d --build