name: laravel-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Copier .env.example → .env
      run: cp .env.example .env

    - name: Installer Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Lancer les conteneurs Docker
      run: docker-compose up -d --build

    - name: Attendre que MySQL soit prêt
      run: |
        echo "Attente de MySQL..."
        sleep 20

    - name: Exécuter les commandes Laravel dans le conteneur
      run: |
        docker exec laravel_app composer install
        docker exec laravel_app php artisan key:generate
        docker exec laravel_app php artisan migrate --force
        docker exec laravel_app php artisan test

    - name: Arrêter les conteneurs
      run: docker-compose down
