name: Laravel Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-ci:
    runs-on: ubuntu-latest

    steps:
      - name:  Cloner le dépôt
        uses: actions/checkout@v3

      - name:  Copier .env.example → .env
        run: cp .env.example .env

      - name:  Lancer les conteneurs Docker
        run: docker-compose up -d --build

      - name:  Attendre que MySQL soit prêt
        run: |
          echo "Attente de MySQL "
          sleep 15

      - name:  Exécuter les commandes Laravel dans le conteneur
        run: |
          docker exec laravel_app php artisan config:clear
          docker exec laravel_app php artisan key:generate
          docker exec laravel_app php artisan migrate --force
          docker exec laravel_app php artisan test

      - name:  Arrêter les conteneurs
        if: always()
        run: docker-compose down
