name: Jira Transition Workflow
on:
  pull_request_target:
    types: [closed]
    branches: [main]

jobs:
  transition-issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Jira Issue Key
        id: extract-key
        run: |
          KEY=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Z]{2,}-[0-9]+' | head -1)
          [ -z "$KEY" ] && KEY=$(echo "${{ github.event.pull_request.head.ref }}" | grep -oE '[A-Z]{2,}-[0-9]+' | head -1)
          echo "issue=${KEY:-NOT_FOUND}" >> $GITHUB_OUTPUT

      - name: Verify Jira Configuration
        run: |
          echo "JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}"
          echo "Issue Key: ${{ steps.extract-key.outputs.issue }}"

      - name: Transition Issue
        if: steps.extract-key.outputs.issue != 'NOT_FOUND'
        uses: atlassian/gajira-transition@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        with:
          issue: ${{ steps.extract-key.outputs.issue }}
          transition: "TERMINÉ(E)"