name: Jira Transition Workflow

on:
  pull_request_target:
    types: [closed]

jobs:
  transition-issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Jira Issue Key
        id: extract-key
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          JIRA_KEY=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Z]{2,}-[0-9]+' | head -1)
          
          if [ -z "$JIRA_KEY" ]; then
            JIRA_KEY=$(echo "${{ github.event.pull_request.head.ref }}" | grep -oE '[A-Z]{2,}-[0-9]+' | head -1)
          fi
          
          if [ -n "$JIRA_KEY" ]; then
            echo "Found Jira issue: $JIRA_KEY"
            echo "issue=$JIRA_KEY" >> $GITHUB_OUTPUT
          else
            echo "No Jira issue found"
            echo "issue=" >> $GITHUB_OUTPUT
          fi

      - name: Get Transition ID
        if: steps.extract-key.outputs.issue != ''
        id: get-transition
        run: |
          JIRA_KEY="${{ steps.extract-key.outputs.issue }}"
          TRANSITION_NAME="TERMINÉ(E)"
          
          # Get available transitions
          TRANSITIONS_RESPONSE=$(curl -s \
            --request GET \
            --url "${{ secrets.JIRA_BASE_URL }}/rest/api/2/issue/${JIRA_KEY}/transitions" \
            --user "${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            --header "Accept: application/json")
          
          # Extract transition ID
          TRANSITION_ID=$(echo $TRANSITIONS_RESPONSE | jq -r --arg NAME "$TRANSITION_NAME" '.transitions[] | select(.name==$NAME) | .id')
          
          if [ -n "$TRANSITION_ID" ]; then
            echo "Found transition ID: $TRANSITION_ID for '$TRANSITION_NAME'"
            echo "transition_id=$TRANSITION_ID" >> $GITHUB_OUTPUT
          else
            echo "No transition found with name: '$TRANSITION_NAME'"
            echo "Available transitions:"
            echo $TRANSITIONS_RESPONSE | jq -r '.transitions[] | .name'
            exit 1
          fi

      - name: Transition Issue
        if: steps.extract-key.outputs.issue != '' && steps.get-transition.outputs.transition_id != ''
        run: |
          JIRA_KEY="${{ steps.extract-key.outputs.issue }}"
          TRANSITION_ID="${{ steps.get-transition.outputs.transition_id }}"
          
          # Make transition request
          RESPONSE=$(curl -s \
            --request POST \
            --url "${{ secrets.JIRA_BASE_URL }}/rest/api/2/issue/${JIRA_KEY}/transitions" \
            --user "${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --data "{\"transition\":{\"id\":\"${TRANSITION_ID}\"}}")
          
          # Check if transition was successful (empty response means success)
          if [ -z "$RESPONSE" ]; then
            echo "Transition successfully applied to $JIRA_KEY"
          else
            echo "Error applying transition: $RESPONSE"
            exit 1
          fi