name: Laravel Docker Workflow

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Copier .env.example → .env
      run: cp .env.example .env

    - name: Installer Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Lancer les conteneurs Docker
      run: docker-compose up -d

    - name: Attendre que MySQL soit prêt
      run: |
        echo "Attente de la disponibilité de MySQL..."
        docker-compose exec -T laravel_app bash -c 'until mysqladmin ping -h"$DB_HOST" --silent; do sleep 2; done'

    - name: Exécuter les commandes Laravel dans le conteneur
      run: |
        docker-compose exec -T laravel_app bash -c "composer install"
        docker-compose exec -T laravel_app bash -c "php artisan key:generate"
        docker-compose exec -T laravel_app bash -c "php artisan migrate"

    - name: Arrêter les conteneurs
      run: docker-compose down
