name: Jira Transition Automation

on:
  pull_request_target:
    types: [closed]

jobs:
  jira-transition:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    
    steps:
      - name: Extract Jira Issue Key
        id: extract_jira_key
        run: |
          sources=(
            "${{ github.event.pull_request.title }}"
            "${{ github.event.pull_request.body }}"
            "${{ github.event.pull_request.head.ref }}"
          )

          for source in "${sources[@]}"; do
            JIRA_KEY=$(echo "$source" | grep -oE '[A-Z]{2,}-[0-9]+' | head -1)
            [ -n "$JIRA_KEY" ] && break
          done

          if [ -n "$JIRA_KEY" ]; then
            echo "issue=$JIRA_KEY" >> $GITHUB_OUTPUT
          else
            echo "issue=" >> $GITHUB_OUTPUT
          fi

      - name: Transition Jira Issue
        if: steps.extract_jira_key.outputs.issue != ''
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.extract_jira_key.outputs.issue }}
          transition: "TERMINÉ(E)"
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}