name: Jira Transition Workflow
on:
  pull_request_target:
    types: [closed]
    branches: [main]

jobs:
  transition-issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Extract Jira Issue Key
        id: extract-key
        run: |
          KEY=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Z]{2,}-[0-9]+' | head -1)
          if [ -z "$KEY" ]; then
            KEY=$(echo "${{ github.event.pull_request.head.ref }}" | grep -oE '[A-Z]{2,}-[0-9]+' | head -1)
          fi
          echo "issue=$KEY" >> $GITHUB_OUTPUT

      - name: Transition Jira Issue
        if: steps.extract-key.outputs.issue != ''
        uses: atlassian/gajira-transition@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        with:
          issue: ${{ steps.extract-key.outputs.issue }}
          transition: "Done"  # Remplacez par le nom exact de votre transition Jira