name: Jira Transition Workflow
on:
  pull_request_target:
    types: [closed]
    branches: [main]

jobs:
  transition-issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Jira Issue Key
        id: extract-key
        run: |
          KEY=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Z]{2,}-[0-9]+' | head -1)
          [ -z "$KEY" ] && KEY=$(echo "${{ github.event.pull_request.head.ref }}" | grep -oE '[A-Z]{2,}-[0-9]+' | head -1)
          echo "issue=${KEY:-NOT_FOUND}" >> $GITHUB_OUTPUT

      - name: Create Jira config file
        run: |
          mkdir -p /home/runner/jira
          cat > /home/runner/jira/config.yml << EOF
          baseUrl: ${{ secrets.JIRA_BASE_URL }}
          email: ${{ secrets.JIRA_USER_EMAIL }}
          apiToken: ${{ secrets.JIRA_API_TOKEN }}
          EOF
          # Verify the config file was created properly
          echo "Config file created at: /home/runner/jira/config.yml"
          ls -la /home/runner/jira/
          cat /home/runner/jira/config.yml

      - name: Transition Jira Issue
        if: steps.extract-key.outputs.issue != 'NOT_FOUND'
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.extract-key.outputs.issue }}
          transition: "TERMINÉ(E)"