name: Jira Transition Workflow
on:
  pull_request_target:
    types: [closed]
    branches: [main]

jobs:
  transition-issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Extract Jira Issue Key
        id: extract-key
        run: |
          KEY=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Z]{2,}-[0-9]+' | head -1)
          if [ -z "$KEY" ]; then
            KEY=$(echo "${{ github.event.pull_request.head.ref }}" | grep -oE '[A-Z]{2,}-[0-9]+' | head -1)
          fi
          echo "issue=$KEY" >> $GITHUB_OUTPUT

      - name: Setup Jira Config
        run: |
          mkdir -p /home/runner/jira
          echo "baseUrl: ${{ secrets.JIRA_BASE_URL }}" > /home/runner/jira/config.yml
          echo "email: ${{ secrets.JIRA_USER_EMAIL }}" >> /home/runner/jira/config.yml
          echo "apiToken: ${{ secrets.JIRA_API_TOKEN }}" >> /home/runner/jira/config.yml

      - name: Validate Transition Name
        run: |
          echo "Transition utilisée : 'TERMINÉ(E)'"
          echo "Vérifiez que ce nom correspond exactement à celui dans Jira (casse et caractères spéciaux)"

      - name: Transition Jira Issue
        if: steps.extract-key.outputs.issue != ''
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.extract-key.outputs.issue }}
          transition: "TERMINÉ(E)"  # Nom exact avec majuscules et caractères spéciaux